config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end
  get 'maps/portland'
  get 'maps/seattle'
 
  get 'pages/about'
  match '/about' => 'pages#about', :via => [:get], as: 'about'
  match '/terms' => 'pages#terms', :via => [:get], as: 'terms'
  match '/pricing' => 'pages#pricing', :via => [:get], as: 'pricing'
  match '/how-it-works' => 'pages#how_it_works', :via => [:get], as: 'how-it-works'
  get 'maps/all' => 'maps#all'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'listings#index'

 

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	if Rails.env.development?

    has_attached_file :image, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg"
    has_attached_file :image_two, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg"
    has_attached_file :image_three, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg"
    
  else

  	has_attached_file :image, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg",
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => ":style/:id_:filename"

    has_attached_file :image_two, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg",
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => ":style/:id_:filename"

    has_attached_file :image_three, :styles => { :xlarge => "100%x300", :thumb => "100x100>" }, :default_url => "noimage.jpg",
	  :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => ":style/:id_:filename"

  end

    validates :title, :description, :price, :duration, :image, :city, :state, :updates, :terms, presence: true
    validates :price, numericality: {greater_than: 0}
    validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)
    belongs_to :user
    has_many :orders
 end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

 def seller
   @listings = Listing.where(user: current_user).order("created_at DESC")
 end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show

    @orders = Order.where(buyer_id: current_user) 
    @purchased = false 

    @orders.each do |order| 
    if order.listing_id == @listing.id 
    @purchased = true 
    end 
    end 

  end

  # GET /listings/new
  def new
    @listing = Listing.new
    
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create

    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    
    
    if current_user.recipient.blank?

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    recipient = Stripe::Recipient.create(
      :name => current_user.name,
      :type => "individual",
      :bank_account => token
    )

     current_user.recipient = recipient.id
    current_user.save
    end

  respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :duration, :street, :city, :state, :image, :image_two, :image_three, :category, :dimensions, :updates, :terms,
       :country, :account_number, :routing_number, :stripeToken)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, that is not your listing."
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="container padbotlg">
<%= form_for @listing, :html => { :multipart => true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript> Javascript is disabled. Order cannot be placed. First enable it in your browser.</noscript>
  </div>


  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <span class="small">(Be as descriptive as possible. Explain everything about your ad space.)</span>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :duration %>
    <span class="small">(Daily, Weekly, Or Monthly?)</span>
    <%= f.text_field :duration, class: "form-control" %>

  </div>

  <div class="form-group">
    <%= f.label :street %>
    <span class="small">(Include street only if your listing is stationary. Will not be moving.)</span>
    <%= f.text_field :street, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dimensions %>
    <span class="small">(Enter the size of your available ad space.)</span>
    <%= f.text_field :dimensions, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= f.label :image %>
    <span class="small">(This is your (best), main image. Shown in search results.)</span>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_two %>
    <span class="small">(Include another image of your space.)</span>
    <%= f.file_field :image_two, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_three %>
    <span class="small">(Include one more image of your space.)</span>
    <%= f.file_field :image_three, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :updates %>
    <span class="small">(Describe how you'll update buyers on their ads once they're up. Peace of mind for your buyers. For example: text a daily photo, emails, or even live video showing that their ad is up.)</span>
    <%= f.text_area :updates, class: "form-control" %>
  </div>

<div class="form-group">
    <%= f.label :terms %>
    <span class="small">(What type of ad messages you will and won't allow, as well as any type of sign material you don't want used. For example, you may only want a yard sign used, and not a banner.)</span>
    <%= f.text_area :terms, class: "form-control" %>
  </div>

<% if current_user.recipient.blank? %>
    <br>
    <h1>Bank Account Information</h1>
    <p class="sm-message">(You'll only need to enter this once.)</p>

    <div class="form-group">
      <%= label_tag :country %>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>
  <% end %>

    <div class="checkbox">

        
          
            <input type="checkbox" name="terms" class="acceptterms" />
              <label for="terms">Before submitting you must click the checkbox acknowledging you've read the Terms page. You agree to
                display your listing for the full purchased amount of time, and you understand that 
                failure to do so can result in legal action from a buyer. </label>
         
     
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>
</div>

app/views/listings/edit.html.erb
<div class="container padbotlg">
<h1>Edit listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/index.html.erb
<!--<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><h3>Now open to the Portland, Oregon market!</h3></strong><br>
  <span>Interested in another market?</span><br><a href="#" class="alert-link">Let Us Know.</a> 
</div>-->
<div class="row padbotlg">

 
<div class="col-md-6 center-block padbot" id="search-wrap">
    <div class="input-group input-group-lg">
      <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
      <input type="text" class="form-control" placeholder="Search Is Coming Very Soon!">
    </div>
</div><!--end search-wrap-->


  <% @listings.each do |listing| %>
  <div class="col-md-6 hm-listing-bx">

<div class="thumbnail">
  <%= link_to image_tag(listing.image.url(:xlarge)), listing %>
       
      <div class="caption">
          <h2 class="center"><%= listing.title %></h2>
          <p><%= truncate listing.description, length: 200 %></p>
          

             <ul class="center">
                  <li class="lgrdpar"><%= number_to_currency(listing.price) %></li>
                  <li class="lgrdpar margbotsm"><%= listing.city %>, <%= listing.state %> </li>
                </ul>

          <div class="btn-wrap center">
           <%= link_to 'View It', listing, class: "btn btn-primary" %>
          </div><!--end btn-wrap-->


      </div><!--end caption-->



       
      
  
  </div><!--end thumbnail-->
</div>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<div class="container padbotlg">
<h1>Listings</h1>


<table class="table table-striped table-bordered">
<tr>
  <th class="center">Image</th>
  <th class="center">Name</th>
  <th class="center">Description</th>
  <th class="center">Price</th>
  <th class="center">City</th>
  <th class="center">State</th>
  <th class="center">Actions</th>
</tr>

 <% @listings.each do |listing| %>
  <tr>
    <td><%= image_tag listing.image.url(:thumb) %></td>
    <td><%= listing.title %></td>
<td><%= listing.description %></td>
<td><%= number_to_currency(listing.price) %></td>
<td><%= listing.city %></td>
<td><%= listing.state %></td>
<td>

<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Action <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "View", listing, class: "btn btn-link" %></li>
    <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
    <li><%= link_to "Delete", listing, method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-link" %></li>
  </ul>
</div>

</td>
</tr>
<% end %>
</table>
<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>
</div>

app/views/listings/show.html.erb
<div class="container padbotlg">
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
    <%= image_tag @listing.image.url %>
     </div>
    <div id="other-imgs">
        <div class="thumbnail">
        <%= image_tag @listing.image_two.url %>
        </div>

        <div class="thumbnail">
        <%= image_tag @listing.image_three.url %>
        </div>
    </div><!--end other-imgs-->
  </div>

  <div class="col-md-6">
    <h3 class="show-title"><%= @listing.title %></h3>
    <p class="show-details"><%= @listing.description %></p>

      <div class="well well-lg center" id="listing-details">
        <h3 class="center lesstop">Space Details</h3>
          <p class="show-sm-details lgpar"><span class="glyphicon glyphicon-usd"><br><%= number_to_currency(@listing.price) %> - <%= @listing.duration %></p>
          <br>
          <p class="show-sm-details"><span class="glyphicon glyphicon-map-marker"></span><br><%= @listing.street %></p>
          <p class="show-sm-details"><%= @listing.city %>, <%= @listing.state %></p>
          <br>
          <p class="show-sm-details"><span class="glyphicon glyphicon-fullscreen"><br><%= @listing.dimensions %></p>
          <br>
          <p class="show-sm-details"><span class="glyphicon glyphicon-list-alt"></span><br><%= @listing.terms %></p>
      </div><!--end listing-details-->

      <div class="well center" id="seller-details">
        <h3 class="center lesstop">Seller Details</h3>
        <p class="show-sm-details"><span class="glyphicon glyphicon-user"></span><br><%= @listing.user.name %></p>
          <% if @purchased %>
          <p class="show-sm-details"><span class="glyphicon glyphicon-envelope"></span><br>Seller Email</p>
          <p class="show-sm-details"><span class="glyphicon glyphicon-earphone"></span><br>Seller Phone</p>
          </div><!--end seller-details-->
          <% else %>
          <p class="show-sm-details red">Seller's contact info provided after purchase.</p>
          <% end %>
      </div><!--end well-->

  <div class="center">
      <%= link_to "Order This Spot", new_listing_order_path(@listing), class: "btn btn-lg btn-primary wht-text" %>
    </div><!end center-->

</div>

<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>