config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end
  get 'maps/portland'
  get 'maps/seattle'
 
  get 'pages/about'
  match '/about' => 'pages#about', :via => [:get], as: 'about'
  match '/terms' => 'pages#terms', :via => [:get], as: 'terms'
  match '/pricing' => 'pages#pricing', :via => [:get], as: 'pricing'
  match '/how-it-works' => 'pages#how_it_works', :via => [:get], as: 'how-it-works'
  get 'maps/all' => 'maps#all'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'listings#index'

 

end

app/views/layouts/_footer.html.erb
<div id="bottom">
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav">
        <li><%= link_to "about", about_path, class: "navlinks" %></li>
        <li><%= link_to "pricing", pricing_path, class: "navlinks" %></li>
        <li><%= link_to "terms", terms_path, class: "navlinks" %></li>
      </ul>  
  </div>
</nav>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">ISEMENT</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     

      

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "how it works", how_it_works_path, class: "navlinks" %></li>
        <li><%= link_to "maps", maps_all_path, class: "navlinks" %></li>
        <% if user_signed_in? %>


<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "your listings", seller_path, class: "navlinks" %></li>
            <li><%= link_to "sales history", sales_path, class: "navlinks" %></li>
            <li><%= link_to "purchase history", purchases_path, class: "navlinks" %></li>
            <li><%= link_to "edit profile", edit_user_registration_path, class: "navlinks" %></li>
            <li><%= link_to "sign-out", destroy_user_session_path, method: :delete, class: "navlinks" %></li>
            
            
          </ul>
        </li>
  <li><%= link_to 'Post A New Listing', new_listing_path, class: "navlinks str-link" %></li>



  <% else %>
        <li><%= link_to "sign-up", new_user_registration_path, class: "navlinks" %></li>
        <li><%= link_to "sign-in", new_user_session_path, class: "navlinks str-link" %></li>
        <% end %>
      </ul>
      
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron center margbot">
<div class="container">
<h1 class="center">Buy & Sell Unique & Clever Advertising Space.</h1>
<p><%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>
</div><!--end jumbotron-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isement</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= javascript_include_tag'https://api.tiles.mapbox.com/mapbox.js/v1.6.4/mapbox.js' %>
<%= javascript_include_tag 'https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.3/Leaflet.fullscreen.min.js' %>
 <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>


<%= render 'layouts/header' %>
<%= render 'layouts/jumbotron' %>
<div class="container padbotlg">
	<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
<div><!--end container-->

</body>
</html>